ARG BASE=nvidia/cuda:12.1.0-devel-ubuntu22.04
FROM ${BASE}

# 定义构建参数
ARG http_proxy
ARG https_proxy

# 设置环境变量
ENV http_proxy=$http_proxy
ENV https_proxy=$https_proxy
ENV DEBIAN_FRONTEND=noninteractive

# 安装系统依赖
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc g++ make git python3 python3-dev python3-pip python3-venv python3-wheel \
    espeak-ng libsndfile1-dev nano vim unzip wget xz-utils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /root
COPY . /root

# 安装 Python 依赖
RUN pip3 install --no-cache-dir -e /root/OpenVoice/ && \
    pip3 install --no-cache-dir -e /root/MeloTTS/ && \
    python3 -m unidic download && \
    pip3 install --no-cache-dir fastapi faster_whisper whisper_timestamped streamlit && \
    rm -rf /root/.cache/pip

# 安装 ffmpeg
RUN wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz && \
    tar -xvf ffmpeg-release-amd64-static.tar.xz -C /tmp && \
    ln -s /tmp/ffmpeg-*/ffmpeg /usr/bin/ffmpeg && \
    ln -s /tmp/ffmpeg-*/ffprobe /usr/bin/ffprobe && \
    rm -rf ffmpeg-release-amd64-static.tar.xz

# 安装 nltk
RUN pip3 install --no-cache-dir nltk && \
    python3 -c "import nltk; nltk.download('cmudict')"

# 清理代理环境变量
ENV http_proxy=""
ENV https_proxy=""

# 设置 PYTHONPATH
ENV PYTHONPATH="/root/OpenVoice/"
